import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    callback request-decrease-value();
    callback request-write-files();
    VerticalBox {
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Decrease value";
            clicked => {
                root.request-decrease-value();
            }
        }
        Button {
            text: "Test Files";
            clicked => {
                root.request-write-files();
            }
        }
        Text {
            text: "This is a simple test!";
        }
        width: parent.width;
        height: parent.height;


    }
}
